### ISSUE TITLE
Cannot find module './config' when 'npm run dev'

### ISSUE THREAD

**Issue by vesper8** [mirror-media/plate-vue#176]
Hello. I was hoping to give this a spin because I wanted to check out your plate-vue-dfp package in action and also I'm interested in the modifications you've made to this package.

I am able to build and run https://github.com/vuejs/vue-hackernews-2.0.git fine

but when I try to run 'npm run dev' on this package after do a 'npm install' I get this error:

``
`
npm run dev

> plate-vue@ dev /plate-vue
> node server

module.js:472
    throw err;
    ^

Error: Cannot find module './config'
```

I also got errors when trying to run 'npm run build'

Just wondering if maybe that's because there are some files missing?

```
npm -v
4.2.0
node -v
v7.8.0
```

any help appreciated! thanks!

**Comment by chiangkeith** [comment]
Hi @vesper8, you have to generate a config file named `config.js` in folder `/api`. In addition the config should be constructed like the file `/api/config.sample.js.`

Hope that's helpful to you.

**Comment by vesper8** [comment]
Hrm ok.. well I just copied the sample into config.js and tried to run npm run dev again and this time getting a different error:

```
~/DEV/__VUE/plate-vue  master  npm run dev

> plate-vue@ dev /DEV/__VUE/plate-vue
> node server

server started at localhost:8080
Connected to Redis http://api.mirrormedia.mg:80
node_redis: Warning: Redis server does not require a password, but a password was supplied.
(node:43353) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
./~/vue-loader/lib/template-compiler.js?id=data-v-35671900!./~/vue-loader/lib/selector.js?type=template&index=0!./src/views/TimelineView.vue
(Emitted value instead of an instance of Error)
  Vue template syntax error:

  tag <div> has no matching end tag.

NonErrorEmittedError: (Emitted value instead of an instance of Error)
  Vue template syntax error:

  tag <div> has no matching end tag.

    at Object.emitError (/DEV/__VUE/plate-vue/node_modules/webpack/lib/NormalModule.js:119:14)
    at /DEV/__VUE/plate-vue/node_modules/vue-loader/lib/template-compiler.js:69:12
    at Array.forEach (native)
    at Object.module.exports (/DEV/__VUE/plate-vue/node_modules/vue-loader/lib/template-compiler.js:68:21)
 @ ./src/views/TimelineView.vue 9:2-169
 @ ./src/router/index.js
 @ ./src/app.js
 @ ./src/server-entry.js
webpack built 9b7314428cc3c08e6734 in 13689ms
Hash: 9b7314428cc3c08e6734
Version: webpack 2.3.3
Time: 13689ms
        Asset     Size  Chunks  Chunk Names
       app.js   3.2 MB       0  app
    vendor.js   318 kB       1  vendor
   app.js.map  4.09 MB       0  app
vendor.js.map   390 kB       1  vendor

WARNING in webpack: Using NoErrorsPlugin is deprecated.
Use NoEmitOnErrorsPlugin instead.


ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-35671900!./~/vue-loader/lib/selector.js?type=template&index=0!./src/views/TimelineView.vue
(Emitted value instead of an instance of Error)
  Vue template syntax error:

  tag <div> has no matching end tag.

 @ ./src/views/TimelineView.vue 9:2-169
 @ ./src/router/index.js
 @ ./src/app.js
 @ ./src/client-entry.js
 @ multi webpack-hot-middleware/client ./src/client-entry.js
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  578 kB       0
webpack: Failed to compile.
http://api.mirrormedia.mg:80
/combo?endpoint=sections&endpoint=choices
save to redis /combo?endpoint=sections&endpoint=choices

events.js:163
      throw er; // Unhandled 'error' event
      ^
ReplyError: ERR syntax error
    at parseError (/DEV/__VUE/plate-vue/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/DEV/__VUE/plate-vue/node_modules/redis-parser/lib/parser.js:303:14)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! plate-vue@ dev: `node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the plate-vue@ dev script 'node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the plate-vue package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs plate-vue
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls plate-vue
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vesperknight/.npm/_logs/2017-04-05T15_24_32_418Z-debug.log
```

Is it possible for me to run it? I can see that your api endpoints are publicly accessible so it should work right?

I'd really like to see this in action on my dev so I can learn from it

**Comment by chiangkeith** [comment]
Hello @vesper8 , of course you can run this project on your local machine. 
There's no problem you can keep the public endpoint for use. 

But if you wanna run it successfully, you need to comment out those codes related to `redis` in file `/api/index.js` and `twitter` stuff in file `timeline.vue` according to the error message mentioned. Because those issues were caused by undefined setting in `/api/config.js`. You don't have the app id for `twitter` and `redis` server, then, of course you'd better comment those codes out.

**Comment by vesper8** [comment]
thanks for the help @chiangkeith! getting closer now

so the error above was actually caused by a missing tag in your TimelineView.vue file

on line 30 the current version is
```
<div class="share mobile-only"></div **<-- missing closing bracket causes error**
```

I actually do have twitter api credentials so I plugged those into the config.js

I also have redis installed so I plugged in the following in the config.js

```
  REDIS_HOST: 'localhost',
  REDIS_PORT: '6379',
```

It was throwing a warning about a password not being needed but one being supplied so I changed this in the api/index.js

```
const redisReadClient = redis.createClient(REDIS_READ_PORT, REDIS_READ_HOST, { no_ready_check: true, password: REDIS_AUTH })
const redisWriteClient = isProd ? redis.createClient(REDIS_WRITE_PORT, REDIS_WRITE_HOST, { no_ready_check: true, password: REDIS_AUTH }) : redisReadClient
```

to

```
const redisReadClient = redis.createClient(REDIS_READ_PORT, REDIS_READ_HOST, {})
const redisWriteClient = isProd ? redis.createClient(REDIS_WRITE_PORT, REDIS_WRITE_HOST, {}) : redisReadClient
```

though I don't think this was causing an actual problem.

npm run dev builds successfully now and runs the server on localhost:8080

however as soon as I try to access it it throws this error:

```
http://api.mirrormedia.mg:80
/combo?endpoint=sections&endpoint=choices
save to redis /combo?endpoint=sections&endpoint=choices

events.js:163
      throw er; // Unhandled 'error' event
      ^
ReplyError: ERR syntax error
    at parseError (/Volumes/Memories/Photos/2012/PictureBright/DEV/__VUE/plate-vue/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/Volumes/Memories/Photos/2012/PictureBright/DEV/__VUE/plate-vue/node_modules/redis-parser/lib/parser.js:303:14)
```

I thought it would try to save on the redis server on my localhost but it seems it's trying to save it on your api? I'm confused about this

I noticed that in your index.js you look for REDIS_READ_HOST, REDIS_READ_PORT, REDIS_WRITE_HOST and REDIS_WRITE_PORT. But those constants are not present in the config.sample.js

So I added them

```
  REDIS_HOST: 'localhost',
  REDIS_PORT: '6379',
  REDIS_READ_HOST: 'localhost',
  REDIS_READ_PORT: '6379',
  REDIS_WRITE_HOST: 'localhost',
  REDIS_WRITE_PORT: '6379',
```

But doing this doesn't help.. I still get the same error. It's still trying to communicate with the redis on your api? But I guess since I don't have the auth password it is failing?

I guess this is happening here

```
                superagent
                    .get(apiHost + req.url)
                    .end((err, response) => {
                        res.send(JSON.parse(response.text))
                        console.log('save to redis', decodeURIComponent(req.url))
                        redisWriteClient.set(decodeURIComponent(req.url), response.text, 'EX', REDIS_TIMEOUT)
                    })
```

I suppose I could just disable this part but I would have preferred to get it working fully locally

Your help would be appreciated :)

Almost there! Thanks!

**Comment by chiangkeith** [comment]
hi @vesper8 , will check your case in days.
